steps:
  MSLV_NATION-e9fc4fb9-d47d-48d8-8f10-2ae2b2726b73:
    operation:
      config:
        storageLocationSearchText: ""
        viewoption: single view
      database: ""
      deployEnabled: true
      description: ""
      isDataVault: false
      isMultisource: false
      locationName: PROD
      materializationType: table
      metadata:
        appliedNodeTests: []
        columns:
          - columnReference:
              columnCounter: 38d25584-8e11-46bd-b96f-1beb1f2bb2d2
              stepCounter: e9fc4fb9-d47d-48d8-8f10-2ae2b2726b73
            dataType: NUMBER(38,0)
            description: ""
            hashColumns: []
            hashDetails: null
            name: N_NATIONKEY
            nullable: false
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: cd6107ab-1c09-4402-bea2-79082fc0072f
                    stepCounter: 1db8e12b-26ff-4588-8870-e973dbc444b2
                transform: ""
          - columnReference:
              columnCounter: 611f549f-80c3-4c3f-883d-d210a7c1da93
              stepCounter: e9fc4fb9-d47d-48d8-8f10-2ae2b2726b73
            dataType: VARCHAR(25)
            description: ""
            hashColumns: []
            hashDetails: null
            name: N_NAME
            nullable: false
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: 6434618d-c779-4389-a6a6-9674b4da4d58
                    stepCounter: 1db8e12b-26ff-4588-8870-e973dbc444b2
                transform: ""
          - columnReference:
              columnCounter: 8abf480b-cb9d-493b-b63d-5bcec4173639
              stepCounter: e9fc4fb9-d47d-48d8-8f10-2ae2b2726b73
            dataType: NUMBER(38,0)
            description: ""
            hashColumns: []
            hashDetails: null
            name: N_REGIONKEY
            nullable: false
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: c71000da-af80-4fa6-93f1-fed96495acb8
                    stepCounter: 1db8e12b-26ff-4588-8870-e973dbc444b2
                transform: ""
          - columnReference:
              columnCounter: 08ffadd9-cd00-40a9-a555-48ddab5e5b6d
              stepCounter: e9fc4fb9-d47d-48d8-8f10-2ae2b2726b73
            dataType: VARCHAR(152)
            description: ""
            hashColumns: []
            hashDetails: null
            name: N_COMMENT
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: 7681ab78-513c-4bf8-a92f-6551ec6e6adc
                    stepCounter: 1db8e12b-26ff-4588-8870-e973dbc444b2
                transform: ""
        cteString: ""
        enabledColumnTestIDs: []
        sourceMapping:
          - customSQL:
              customSQL: ""
            dependencies:
              - locationName: SRC
                nodeName: NATION
            join:
              joinCondition: FROM {{ ref('SRC', 'NATION') }} "NATION"
            name: MSLV_NATION
            noLinkRefs: []
      name: MSLV_NATION
      overrideSQL: false
      schema: ""
      sqlType: "2"
      type: sql
    stepCounter: e9fc4fb9-d47d-48d8-8f10-2ae2b2726b73
