steps:
  FCT_NATION-35ab4406-3874-495a-8bfd-e7c2fe82ea94:
    operation:
      config:
        postSQL: ""
        preSQL: ""
        testsEnabled: true
      database: ""
      deployEnabled: true
      description: ""
      isDataVault: false
      isMultisource: false
      locationName: PROD
      materializationType: table
      metadata:
        appliedNodeTests: []
        columns:
          - columnReference:
              columnCounter: 9733852e-7974-407f-9620-2b270a5f9a0c
              stepCounter: 35ab4406-3874-495a-8bfd-e7c2fe82ea94
            dataType: NUMBER(38,0)
            description: ""
            hashColumns: []
            hashDetails: null
            name: N_NATIONKEY
            nullable: false
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: cd6107ab-1c09-4402-bea2-79082fc0072f
                    stepCounter: 1db8e12b-26ff-4588-8870-e973dbc444b2
                transform: ""
          - columnReference:
              columnCounter: cb9a86d3-d69d-4f7b-a046-b2c98de6b426
              stepCounter: 35ab4406-3874-495a-8bfd-e7c2fe82ea94
            dataType: VARCHAR(25)
            description: ""
            hashColumns: []
            hashDetails: null
            name: N_NAME
            nullable: false
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: 6434618d-c779-4389-a6a6-9674b4da4d58
                    stepCounter: 1db8e12b-26ff-4588-8870-e973dbc444b2
                transform: ""
          - columnReference:
              columnCounter: 90e217d8-10ca-47d6-9a08-267a01bf079a
              stepCounter: 35ab4406-3874-495a-8bfd-e7c2fe82ea94
            dataType: NUMBER(38,0)
            description: ""
            hashColumns: []
            hashDetails: null
            name: N_REGIONKEY
            nullable: false
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: c71000da-af80-4fa6-93f1-fed96495acb8
                    stepCounter: 1db8e12b-26ff-4588-8870-e973dbc444b2
                transform: ""
          - columnReference:
              columnCounter: 9509982c-7d74-48b8-bf66-7f733b56abb5
              stepCounter: 35ab4406-3874-495a-8bfd-e7c2fe82ea94
            dataType: VARCHAR(152)
            description: ""
            hashColumns: []
            hashDetails: null
            name: N_COMMENT
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: 7681ab78-513c-4bf8-a92f-6551ec6e6adc
                    stepCounter: 1db8e12b-26ff-4588-8870-e973dbc444b2
                transform: ""
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 33886f55-525f-4ee0-b416-90db6705ba85
              stepCounter: 35ab4406-3874-495a-8bfd-e7c2fe82ea94
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            hashColumns: []
            isSystemCreateDate: true
            name: SYSTEM_CREATE_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST(CURRENT_TIMESTAMP AS TIMESTAMP)
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: e960115d-d9ab-4d5c-ba29-8c17f29b6266
              stepCounter: 35ab4406-3874-495a-8bfd-e7c2fe82ea94
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            hashColumns: []
            isSystemUpdateDate: true
            name: SYSTEM_UPDATE_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST(CURRENT_TIMESTAMP AS TIMESTAMP)
        cteString: ""
        enabledColumnTestIDs: []
        sourceMapping:
          - customSQL:
              customSQL: ""
            dependencies:
              - locationName: SRC
                nodeName: NATION
            join:
              joinCondition: FROM {{ ref('SRC', 'NATION') }} "NATION"
            name: FCT_NATION
            noLinkRefs: []
      name: FCT_NATION
      overrideSQL: false
      schema: ""
      sqlType: Fact
      type: sql
    stepCounter: 35ab4406-3874-495a-8bfd-e7c2fe82ea94
