steps:
  PSTG_NATION-5c495f41-9475-413d-8ec3-f87cffe5a18a:
    operation:
      config:
        postSQL: ""
        preSQL: ""
        testsEnabled: true
      database: ""
      deployEnabled: true
      description: ""
      isDataVault: false
      isMultisource: false
      locationName: PROD
      materializationType: table
      metadata:
        appliedNodeTests: []
        columns:
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: b8a60bb6-602b-481e-8240-cf41347d0c66
              stepCounter: 5c495f41-9475-413d-8ec3-f87cffe5a18a
            config: {}
            dataType: NUMBER
            defaultValue: ""
            description: ""
            hashColumns: []
            isSurrogateKey: true
            name: PSTG_NATION_KEY
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: ""
          - columnReference:
              columnCounter: 8401e3da-983e-4bb9-bab3-e376f7f07828
              stepCounter: 5c495f41-9475-413d-8ec3-f87cffe5a18a
            dataType: NUMBER(38,0)
            description: ""
            hashColumns: []
            hashDetails: null
            name: N_NATIONKEY
            nullable: false
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: cd6107ab-1c09-4402-bea2-79082fc0072f
                    stepCounter: 1db8e12b-26ff-4588-8870-e973dbc444b2
                transform: ""
          - columnReference:
              columnCounter: 793fc7c1-0157-4b39-b0be-eefd3017b263
              stepCounter: 5c495f41-9475-413d-8ec3-f87cffe5a18a
            dataType: VARCHAR(25)
            description: ""
            hashColumns: []
            hashDetails: null
            name: N_NAME
            nullable: false
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: 6434618d-c779-4389-a6a6-9674b4da4d58
                    stepCounter: 1db8e12b-26ff-4588-8870-e973dbc444b2
                transform: ""
          - columnReference:
              columnCounter: 9c661a3c-cefe-4556-8b45-a8104eb5d0d0
              stepCounter: 5c495f41-9475-413d-8ec3-f87cffe5a18a
            dataType: NUMBER(38,0)
            description: ""
            hashColumns: []
            hashDetails: null
            name: N_REGIONKEY
            nullable: false
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: c71000da-af80-4fa6-93f1-fed96495acb8
                    stepCounter: 1db8e12b-26ff-4588-8870-e973dbc444b2
                transform: ""
          - columnReference:
              columnCounter: d077b6f2-a4be-4aad-b4a4-ac45294496c5
              stepCounter: 5c495f41-9475-413d-8ec3-f87cffe5a18a
            dataType: VARCHAR(152)
            description: ""
            hashColumns: []
            hashDetails: null
            name: N_COMMENT
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: 7681ab78-513c-4bf8-a92f-6551ec6e6adc
                    stepCounter: 1db8e12b-26ff-4588-8870-e973dbc444b2
                transform: ""
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 6edc128d-a4ea-4e4a-965a-eea9ee50591e
              stepCounter: 5c495f41-9475-413d-8ec3-f87cffe5a18a
            config: {}
            dataType: NUMBER
            defaultValue: ""
            description: ""
            hashColumns: []
            isSystemVersion: true
            name: SYSTEM_VERSION
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: ""
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: fad2de3f-ef52-4f95-a1e0-4d5bc4f64170
              stepCounter: 5c495f41-9475-413d-8ec3-f87cffe5a18a
            config: {}
            dataType: VARCHAR
            defaultValue: ""
            description: ""
            hashColumns: []
            isSystemCurrentFlag: true
            name: SYSTEM_CURRENT_FLAG
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: ""
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: e0a7b958-663e-48f4-8fd8-2b3da9b1d1d9
              stepCounter: 5c495f41-9475-413d-8ec3-f87cffe5a18a
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            hashColumns: []
            isSystemStartDate: true
            name: SYSTEM_START_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST(CURRENT_TIMESTAMP AS TIMESTAMP)
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: ae38def2-09ec-4caa-a8c1-338658c9cb1e
              stepCounter: 5c495f41-9475-413d-8ec3-f87cffe5a18a
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            hashColumns: []
            isSystemEndDate: true
            name: SYSTEM_END_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST('2999-12-31 00:00:00' AS TIMESTAMP)
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 89e45e4d-d339-4498-aea0-6d1e9ba13dc1
              stepCounter: 5c495f41-9475-413d-8ec3-f87cffe5a18a
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            hashColumns: []
            isSystemCreateDate: true
            name: SYSTEM_CREATE_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST(CURRENT_TIMESTAMP AS TIMESTAMP)
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: fa4839b1-09ab-4341-aabf-0e0786f9303f
              stepCounter: 5c495f41-9475-413d-8ec3-f87cffe5a18a
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            hashColumns: []
            isSystemUpdateDate: true
            name: SYSTEM_UPDATE_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST(CURRENT_TIMESTAMP AS TIMESTAMP)
        cteString: ""
        enabledColumnTestIDs: []
        sourceMapping:
          - customSQL:
              customSQL: ""
            dependencies:
              - locationName: SRC
                nodeName: NATION
            join:
              joinCondition: FROM {{ ref('SRC', 'NATION') }} "NATION"
            name: PSTG_NATION
            noLinkRefs: []
      name: PSTG_NATION
      overrideSQL: false
      schema: ""
      sqlType: persistentStage
      type: sql
    stepCounter: 5c495f41-9475-413d-8ec3-f87cffe5a18a
