steps:
  DIM_NATION-5f766c67-3670-492d-b4be-0acdeee52765:
    operation:
      config:
        postSQL: ""
        preSQL: ""
        testsEnabled: true
      database: ""
      deployEnabled: true
      description: ""
      isDataVault: false
      isMultisource: false
      locationName: PROD
      materializationType: table
      metadata:
        appliedNodeTests: []
        columns:
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 30e00e0b-40a3-48bd-84c2-5275233c6bea
              stepCounter: 5f766c67-3670-492d-b4be-0acdeee52765
            config: {}
            dataType: NUMBER
            defaultValue: ""
            description: ""
            hashColumns: []
            isSurrogateKey: true
            name: DIM_NATION_KEY
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: ""
          - columnReference:
              columnCounter: 7da5d63d-e4cb-4cb1-860b-0d55b3917400
              stepCounter: 5f766c67-3670-492d-b4be-0acdeee52765
            dataType: NUMBER(38,0)
            description: ""
            hashColumns: []
            hashDetails: null
            isBusinessKey: true
            name: N_NATIONKEY
            nullable: false
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: cd6107ab-1c09-4402-bea2-79082fc0072f
                    stepCounter: 1db8e12b-26ff-4588-8870-e973dbc444b2
                transform: ""
          - columnReference:
              columnCounter: 5d3dbf48-e33c-41c9-b801-2b24ee91994c
              stepCounter: 5f766c67-3670-492d-b4be-0acdeee52765
            dataType: VARCHAR(25)
            description: ""
            hashColumns: []
            hashDetails: null
            name: N_NAME
            nullable: false
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: 6434618d-c779-4389-a6a6-9674b4da4d58
                    stepCounter: 1db8e12b-26ff-4588-8870-e973dbc444b2
                transform: ""
          - columnReference:
              columnCounter: acfb32cf-74b2-4832-a61a-8a0c7112aa93
              stepCounter: 5f766c67-3670-492d-b4be-0acdeee52765
            dataType: NUMBER(38,0)
            description: ""
            hashColumns: []
            hashDetails: null
            name: N_REGIONKEY
            nullable: false
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: c71000da-af80-4fa6-93f1-fed96495acb8
                    stepCounter: 1db8e12b-26ff-4588-8870-e973dbc444b2
                transform: ""
          - columnReference:
              columnCounter: b34bb72b-8b8e-4376-896c-fd561ff14495
              stepCounter: 5f766c67-3670-492d-b4be-0acdeee52765
            dataType: VARCHAR(152)
            description: ""
            hashColumns: []
            hashDetails: null
            name: N_COMMENT
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: 7681ab78-513c-4bf8-a92f-6551ec6e6adc
                    stepCounter: 1db8e12b-26ff-4588-8870-e973dbc444b2
                transform: ""
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 1dfe76fe-ce2f-42aa-a143-ce90492567c9
              stepCounter: 5f766c67-3670-492d-b4be-0acdeee52765
            config: {}
            dataType: NUMBER
            defaultValue: ""
            description: ""
            hashColumns: []
            isSystemVersion: true
            name: SYSTEM_VERSION
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: ""
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: e8634049-b70b-470e-90ae-ab0f7a91dd66
              stepCounter: 5f766c67-3670-492d-b4be-0acdeee52765
            config: {}
            dataType: VARCHAR
            defaultValue: ""
            description: ""
            hashColumns: []
            isSystemCurrentFlag: true
            name: SYSTEM_CURRENT_FLAG
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: ""
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 541c71d3-9325-4e29-b724-9645c1440995
              stepCounter: 5f766c67-3670-492d-b4be-0acdeee52765
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            hashColumns: []
            isSystemStartDate: true
            name: SYSTEM_START_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST(CURRENT_TIMESTAMP AS TIMESTAMP)
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 7aadff88-f579-4c9c-ae6e-315939e65eda
              stepCounter: 5f766c67-3670-492d-b4be-0acdeee52765
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            hashColumns: []
            isSystemEndDate: true
            name: SYSTEM_END_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST('2999-12-31 00:00:00' AS TIMESTAMP)
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 60aaf3c2-5c93-4904-9c7e-3d6c960ed827
              stepCounter: 5f766c67-3670-492d-b4be-0acdeee52765
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            hashColumns: []
            isSystemCreateDate: true
            name: SYSTEM_CREATE_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST(CURRENT_TIMESTAMP AS TIMESTAMP)
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: e04aabd4-e70b-4870-8e04-8a025f1f7ac6
              stepCounter: 5f766c67-3670-492d-b4be-0acdeee52765
            config: {}
            dataType: TIMESTAMP
            defaultValue: ""
            description: ""
            hashColumns: []
            isSystemUpdateDate: true
            name: SYSTEM_UPDATE_DATE
            nullable: true
            sourceColumnReferences:
              - columnReferences: []
                transform: CAST(CURRENT_TIMESTAMP AS TIMESTAMP)
        cteString: ""
        enabledColumnTestIDs: []
        sourceMapping:
          - customSQL:
              customSQL: ""
            dependencies:
              - locationName: SRC
                nodeName: NATION
            join:
              joinCondition: FROM {{ ref('SRC', 'NATION') }} "NATION"
            name: DIM_NATION
            noLinkRefs: []
      name: DIM_NATION
      overrideSQL: false
      schema: ""
      sqlType: Dimension
      type: sql
    stepCounter: 5f766c67-3670-492d-b4be-0acdeee52765
